sources:
  - name: lrs
    schema: alrs
    tables:
      - name: road_network_nat

  - name: misc
    schema: MISC
    tables:
      - name: MAP_PPK_ROUTE
      - name: MAP_BALAI_ROUTE
      - name: MAP_BALAI_PROV
      - name: MAP_PROV_ROUTE
      - name: REF_PROVINCE