{% macro kemantapan_sk_columns(base_alias = 'base', lrs_alias = 'lrs') %}
({{base_alias}}.P_GOOD_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as P_GOOD_KM,
({{base_alias}}.P_FAIR_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as P_FAIR_KM,
({{base_alias}}.P_POOR_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as P_POOR_KM,
({{base_alias}}.P_BAD_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as P_BAD_KM,
({{base_alias}}.UP_GOOD_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as UP_GOOD_KM,
({{base_alias}}.UP_FAIR_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as UP_FAIR_KM,
({{base_alias}}.UP_POOR_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as UP_POOR_KM,
({{base_alias}}.UP_BAD_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as UP_BAD_KM,
({{base_alias}}.MANTAP_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as MANTAP_KM,
({{base_alias}}.TDK_MANTAP_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as TDK_MANTAP_KM,
({{base_alias}}.P_MANTAP_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as P_MANTAP_KM,
({{base_alias}}.P_TDK_MANTAP_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as P_TDK_MANTAP_KM,
({{base_alias}}.UP_MANTAP_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as UP_MANTAP_KM,
({{base_alias}}.UP_TDK_MANTAP_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as UP_TDK_MANTAP_KM,
({{base_alias}}.GOOD_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as GOOD_KM,
({{base_alias}}.FAIR_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as FAIR_KM,
({{base_alias}}.POOR_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as POOR_KM,
({{base_alias}}.BAD_KM * ({{lrs_alias}}.SK_LENGTH/{{base_alias}}.TOTAL_LENGTH)) as BAD_KM,

{{base_alias}}.MANTAP_PSN,
{{base_alias}}.TDK_MANTAP_PSN,
{{base_alias}}.P_MANTAP_PSN,
{{base_alias}}.P_TDK_MANTAP_PSN,
{{base_alias}}.UP_MANTAP_PSN,
{{base_alias}}.UP_TDK_MANTAP_PSN,
{{base_alias}}.GOOD_PSN,
{{base_alias}}.FAIR_PSN,
{{base_alias}}.POOR_PSN,
{{base_alias}}.BAD_PSN,
{{base_alias}}.P_GOOD_PSN,
{{base_alias}}.P_FAIR_PSN,
{{base_alias}}.P_POOR_PSN,
{{base_alias}}.P_BAD_PSN,
{{base_alias}}.UP_GOOD_PSN,
{{base_alias}}.UP_FAIR_PSN,
{{base_alias}}.UP_POOR_PSN,
{{base_alias}}.UP_BAD_PSN
{% endmacro %}
