"""
SQL query builders.

Every function in this module returns a SQL **string** that is byte-for-byte
identical (modulo whitespace) to the query generated by the legacy
``SMD_Package`` classes.  This is the primary defence against numerical drift.
"""

import numpy as np
import pandas as pd
from .smd_config import SMDConfigs
from . import config


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _get_veh_columns(connection, rtc_table, prefix='NUM_VEH'):
    """
    Discover vehicle columns from the RTC table header.
    Mirrors ``TrafficSummary.veh_columns``.
    """
    df = pd.read_sql(f"select * from {rtc_table} where rownum=1", con=connection)
    cols = np.array(df.columns.tolist())
    mask = np.char.startswith(cols, prefix)
    vehs = cols[mask]
    vehs.sort()
    return vehs.tolist()


# ---------------------------------------------------------------------------
# AADT queries  (TrafficSummary.post_class_aadt_sql)
# ---------------------------------------------------------------------------
def post_class_aadt_sql(routes, year, connection,
                        routeid_col='LINKID',
                        date_col='SURVEY_DATE',
                        hour_col='SURVEY_HOURS',
                        minute_col='SURVEY_MINUTE',
                        class_col='TRAFPOST',
                        temp_route_table='TEMP_REKAP_ROUTE_SELECTION',
                        postdesc_table='POSTDESC',
                        postdesc_prov='NOPROP',
                        postdesc_route='RUAS',
                        postdesc_sffx='SFFX',
                        postclass_table='POST_CLASS',
                        rtc_table=None):
    """
    Build the SQL that computes post-class AADT.
    """
    if rtc_table is None:
        rtc_table = config.RTC_TABLE_FMT.format(year=year)

    # Discover vehicle columns dynamically (same as legacy code)
    veh_columns = _get_veh_columns(connection, rtc_table, prefix=config.VEHICLE_COL_PREFIX)

    # ---- Level 1: RTC grouped by survey window --------------------------------
    rtc_select = (
        f"SELECT {routeid_col}, {date_col}, {hour_col}, {minute_col}, "
        f"substr(stats_mode(b.{class_col}), 1, 1) as {class_col}"
    )

    for num_veh_col in veh_columns:
        rtc_select += f"\n,SUM({num_veh_col}) as {num_veh_col}"

    if str(routes) != 'ALL':
        rtc_from = (
            f"\nFROM {rtc_table} a \n"
            f"LEFT JOIN {postdesc_table} b \n"
            f"ON a.{routeid_col} = CONCAT(CONCAT(b.{postdesc_prov}, b.{postdesc_route}), REPLACE(b.{postdesc_sffx}, ' ', ''))\n"
            f"WHERE {routeid_col} IN (SELECT {routeid_col} FROM {temp_route_table})\n"
            f"GROUP BY {routeid_col}, {date_col}, {hour_col}, {minute_col}"
        )
    else:
        rtc_from = (
            f"\nFROM {rtc_table} a \n"
            f"LEFT JOIN {postdesc_table} b \n"
            f"ON a.{routeid_col} = CONCAT(CONCAT(b.{postdesc_prov}, b.{postdesc_route}), REPLACE(b.{postdesc_sffx}, ' ', ''))\n"
            f"GROUP BY {routeid_col}, {date_col}, {hour_col}, {minute_col}"
        )

    rtc_select = rtc_select + rtc_from

    # ---- Level 2: Window sums & COUNT_HOUR ------------------------------------
    count_hour = (
        f"\n, CASE WHEN {class_col}='C' then"
        f"\nCOUNT({routeid_col}) OVER (PARTITION BY {routeid_col} ORDER BY {date_col}, {hour_col}, {minute_col} ROWS BETWEEN CURRENT ROW AND 63 FOLLOWING)*15/60.0 "
        f"ELSE COUNT({routeid_col}) OVER (PARTITION BY {routeid_col} ORDER BY {date_col}, {hour_col}, {minute_col} ROWS BETWEEN CURRENT ROW AND 159 FOLLOWING)*15/60.0 END AS COUNT_HOUR"
    )

    window_select = (
        f"SELECT {routeid_col}, {class_col}, TO_CHAR({date_col}, 'DAY') as SURVEY_DAY, "
        f"{hour_col}, {minute_col}"
    )

    for num_veh_col in veh_columns:
        window_select += (
            f"\n, CASE WHEN {class_col}='C' then "
            f"\nSUM({num_veh_col}) OVER (PARTITION BY {routeid_col} ORDER BY {date_col}, {hour_col}, {minute_col} ROWS BETWEEN CURRENT ROW AND 63 FOLLOWING)"
            f"\nELSE SUM({num_veh_col}) OVER (PARTITION BY {routeid_col} ORDER BY {date_col}, {hour_col}, {minute_col} ROWS BETWEEN CURRENT ROW AND 159 FOLLOWING) END AS {num_veh_col}"
        )

    window_select = window_select + count_hour + "\nFROM (\n" + rtc_select + "\n)"

    # ---- Level 3: Average multiplied by day factor ----------------------------
    final_select = f"SELECT {routeid_col}"

    for num_veh_col in veh_columns:
        final_select += (
            f"\n, CAST((CASE WHEN STATS_MODE({class_col})='C' THEN AVG({num_veh_col})*MAX(CLASS_1)"
            f" ELSE AVG({num_veh_col})*MAX(CLASS_2) END) AS INT) AS {num_veh_col}"
        )

    final_select = (
        final_select + "\nFROM (\n" + window_select + "\n)"
        f"LEFT JOIN {postclass_table} ON REPLACE(SURVEY_DAY, ' ', '') = DAY_OF_WEEK\n"
        f"WHERE (({hour_col} = 6 and {minute_col} = 0) or ({hour_col} = 5 and {minute_col} = 60)) and (COUNT_HOUR = 40 OR COUNT_HOUR = 16)\n"
        f"GROUP BY {routeid_col}"
    )

    return final_select


# ---------------------------------------------------------------------------
# RNI queries  (TrafficVolume.get_rni_data_sql)
# ---------------------------------------------------------------------------
def get_rni_data_sql(routes, rni_table, temp_route_table='TEMP_REKAP_ROUTE_SELECTION',
                     routeid_col='LINKID',
                     from_m_col='FROM_STA',
                     to_m_col='TO_STA',
                     lane_width='LANE_WIDTH',
                     left_terr='LEFT_TERRAIN',
                     right_terr='RIGHT_TERRAIN',
                     road_type_col='ROAD_TYPE'):
    """
    Build the SQL that returns one aggregated row per route from the RNI table.
    """

    if str(routes) == 'ALL':
        segment_groupby = (
            f"SELECT {routeid_col}, {from_m_col}, {to_m_col},"
            f"sum({lane_width}) as {lane_width}, "
            f"greatest(max(substr({left_terr},2,1)), max(substr({right_terr},2,1))) as TERR \n"
            f"FROM {rni_table}\n"
            f"GROUP BY {routeid_col}, {from_m_col}, {to_m_col}"
        )

        route_type_groupby = (
            f"SELECT {routeid_col}, \n "
            f"MAX({road_type_col}) KEEP (DENSE_RANK FIRST ORDER BY C_TYPE DESC, ROAD_TYPE DESC) AS {road_type_col} \n"
            f"FROM \n (SELECT {routeid_col}, COUNT({road_type_col}) AS C_TYPE, {road_type_col}\n"
            f"FROM {rni_table}\n "
            f"GROUP BY {routeid_col}, {road_type_col})\n "
            f"GROUP BY {routeid_col}"
        )
    else:
        segment_groupby = (
            f"SELECT {routeid_col}, {from_m_col}, {to_m_col},"
            f"sum({lane_width}) as {lane_width}, "
            f"greatest(nvl(max(substr({left_terr},2,1)), 0), nvl(max(substr({right_terr},2,1)), 0)) as TERR \n"
            f"FROM {rni_table}\n"
            f"WHERE {routeid_col} IN (SELECT {routeid_col} FROM {temp_route_table})\n"
            f"GROUP BY {routeid_col}, {from_m_col}, {to_m_col}"
        )

        route_type_groupby = (
            f"SELECT {routeid_col}, \n "
            f"MAX({road_type_col}) KEEP (DENSE_RANK FIRST ORDER BY C_TYPE DESC, ROAD_TYPE DESC) AS {road_type_col} \n"
            f"FROM \n (SELECT {routeid_col}, COUNT({road_type_col}) AS C_TYPE, {road_type_col}\n"
            f"FROM {rni_table}\n "
            f"WHERE {routeid_col} IN (SELECT {routeid_col} FROM {temp_route_table})\n "
            f"GROUP BY {routeid_col}, {road_type_col})\n "
            f"GROUP BY {routeid_col}"
        )

    route_terr_groupby = (
        f"SELECT {routeid_col}, TERR, COUNT(TERR) as C_TERR, "
        f"AVG({lane_width}) as {lane_width} \nFROM (\n"
    )
    route_terr_groupby = route_terr_groupby + segment_groupby + "\n) GROUP BY LINKID, TERR"

    route_terr_lane_w = (
        f"SELECT {routeid_col}, "
        f"\nMAX(TERR) KEEP (DENSE_RANK FIRST ORDER BY C_TERR DESC, TERR ASC) AS TERR,"
        f"\nAVG({lane_width}) as {lane_width} "
        f"FROM(\n"
    )
    route_terr_lane_w = route_terr_lane_w + route_terr_groupby + "\n) GROUP BY LINKID"

    final_select = (
        f"SELECT a.*, b.{road_type_col} \nFROM (" + route_terr_lane_w + ") a \nLEFT JOIN (" +
        route_type_groupby + f") b \nON a.{routeid_col} = b.{routeid_col}"
    )

    return final_select


# ---------------------------------------------------------------------------
# Capacity queries  (RoadCapacity.segment_capacity_sql & calculate_capacity)
# ---------------------------------------------------------------------------
def segment_capacity_sql(routes, year, aadt_df_sql, rni_table, temp_route_table,
                         capacity_coeff_table='CAPACITY_COEFF',
                         routeid_col='LINKID',
                         from_m_col='FROM_STA',
                         to_m_col='TO_STA',
                         segment_len_col='SEGMENT_LENGTH',
                         lane_width='LANE_WIDTH',
                         road_type_col='ROAD_TYPE',
                         left_terr='LEFT_TERRAIN',
                         right_terr='RIGHT_TERRAIN',
                         left_inner_sh_w='LEFT_INNER_SH_W',
                         left_outer_sh_w='LEFT_OUTER_SH_W',
                         right_inner_sh_w='RIGHT_INNER_SH_W',
                         right_outer_sh_w='RIGHT_OUTER_SH_W',
                         veh8_col='NUM_VEH8'):
    """
    Build the SQL that calculates capacity for every RNI segment.
    """

    # -- RNI subquery (aggregated per route/from_m) ----------------------------
    from .rni_summary import road_type_group_df as _rtg_df
    road_type_group_df = _rtg_df()
    road_type_group_series = road_type_group_df.groupby('ROAD_TYPE_GROUP')['ROAD_TYPE'].apply(lambda x: list(x))

    road_type_case = None
    for road_type_group, group_list in road_type_group_series.items():
        list_str = str(group_list).replace('[', '(').replace(']', ')')
        case = f" WHEN MAX({road_type_col}) IN {list_str} THEN {road_type_group}"
        if road_type_case is None:
            road_type_case = "CASE" + case
        else:
            road_type_case += case
    road_type_case += f" ELSE 0 END AS {road_type_col}"

    if str(routes) != 'ALL':
        rni_select = (
            f"SELECT {routeid_col}, {from_m_col}, \n"
            f"MAX({to_m_col}) as {to_m_col},"
            f"MAX({segment_len_col}) as {segment_len_col},"
            f"max(nvl(SUBSTR({left_terr}, 2, 1), 0)) as MAX_TERR_L, \n"
            f"max(nvl(SUBSTR({right_terr}, 2, 1), 0)) as MAX_TERR_R, \n"
            f"SUM({lane_width}) as {lane_width}, \n"
            f"SUM(nvl({left_inner_sh_w}, 0)) + SUM(nvl({left_outer_sh_w}, 0)) + SUM(nvl({right_inner_sh_w}, 0)) + "
            f"SUM(nvl({right_outer_sh_w}, 0)) as SHWIDTH, \n" + road_type_case +
            f"\nFROM {rni_table} \n"
            f"WHERE {routeid_col} IN (SELECT {routeid_col} FROM {temp_route_table}) \n"
            f"GROUP BY {routeid_col}, {from_m_col}"
        )
    else:
        rni_select = (
            f"SELECT {routeid_col}, {from_m_col}, \n"
            f"MAX({to_m_col}) as {to_m_col},"
            f"MAX({segment_len_col}) as {segment_len_col},"
            f"SUBSTR(MAX({left_terr}), 2, 1) as MAX_TERR_L, \n"
            f"SUBSTR(MAX({right_terr}), 2, 1) as MAX_TERR_R, \n"
            f"SUM({lane_width}) as {lane_width}, \n"
            f"SUM({left_inner_sh_w}) + SUM({left_outer_sh_w}) + SUM({right_inner_sh_w}) + "
            f"SUM({right_outer_sh_w}) as SHWIDTH, \n" + road_type_case +
            f"\nFROM {rni_table} \n"
            f"GROUP BY {routeid_col}, {from_m_col}"
        )

    # -- AADT subquery ---------------------------------------------------------
    aadt_select = aadt_df_sql

    # -- Join RNI + AADT -------------------------------------------------------
    rni_aadt_join = (
        f"SELECT t1.*, t2.{veh8_col}, "
        f"GREATEST(t1.MAX_TERR_L, t1.MAX_TERR_R) as MAX_TERR \n"
        f"FROM (\n{aadt_select}\n) t2\n"
        f"LEFT JOIN \n(\n{rni_select}\n) t1\n"
        f"ON t1.{routeid_col} = t2.{routeid_col}"
    )

    # -- Capacity formula (FCSF, FCSP, FCW) ------------------------------------
    fcsf = (
        "("
        "coeff.F1 - "
        "LEAST("
        "("
        f"coeff.F2*POWER(GREATEST((LEAST(joined.{veh8_col}, 2300)-200), 0), coeff.F3) +\n"
        f"POWER(coeff.F4*GREATEST((joined.SHWIDTH-0.5), 0), coeff.F5) *\n"
        f"GREATEST((LEAST(joined.{veh8_col}, 2300)-coeff.F6), 0)"
        ")"
        ", 0)"
        ")"
    )

    fcsp = "(0.97)"

    fcw = f"(coeff.W1 + coeff.W2*(joined.{lane_width}) + coeff.W3*POWER(joined.{lane_width}, 2))"

    cap = "(" + "coeff.BASE*" + fcw + "*" + fcsp + "*" + fcsf + ") as CAP"

    coeff_join = (
        f"SELECT joined.{routeid_col}, joined.{from_m_col}, joined.{to_m_col}, "
        f"joined.{segment_len_col}, " + cap +
        f"\nFROM\n({rni_aadt_join}\n) joined\n"
        f"LEFT JOIN\n({capacity_coeff_table}\n) coeff\n"
        f"on joined.{road_type_col} = coeff.ROAD_TYPE\n"
        f"AND joined.MAX_TERR = coeff.TERRAIN"
    )

    return coeff_join


def calculate_capacity_sql(segment_capacity_sql, routeid_col='LINKID',
                           segment_len_col='SEGMENT_LENGTH', year=2021):
    """
    Wrap ``segment_capacity_sql`` in the weighted-average GROUP BY.
    """
    return (
        f"SELECT {routeid_col}, SUM(CAP*{segment_len_col})/SUM({segment_len_col}) WEIGHTED_CAP,"
        f"{year} AS YEAR\n "
        f"FROM\n({segment_capacity_sql}\n)\n GROUP BY {routeid_col}"
    )
